# /swagger/project.yaml

components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
          description: 프로젝트 아이디
          example: 1
        imageId:
          type: integer
          description: 이미지 id
          example: 1
        userId:
          type: integer
          description: 유저 id
          example: 1
        title:
          type: string
          description: 제목
          example: 제목
        intro:
          type: string
          description: 내용
          example: 내용
        content:
          type: string
          description: 내용
          example: 내용
        likeCount:
          type: integer
          description: 좋아요 수
          example: 0
        createdAt:
          type: string
          description: 생성일
          example: 2023-02-17 14:32:11.893
        updatedAt:
          type: string
          description: 수정일
          example: 2023-02-17 14:32:11.893
